# Generated by Django 5.1.3 on 2024-11-15 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrainwaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('af7', models.IntegerField()),
                ('af8', models.IntegerField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brainwave_data', to='neuromanceDB.individual')),
            ],
        ),
    ]
