# Generated by Django 5.1.3 on 2024-11-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuromanceDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='individual',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
